export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const RELOAD_REQUIRED = 'RELOAD_REQUIRED';
export const API_FAILED_ERROR = 'API_FAILED_ERROR';
export const DONT_SHOW_ERROR_ALERT = 'DONT_SHOW_ERROR_ALERT';

export const ADD_COMMENT = 'COMMENT_ADD';
