export const Common = {
  quickLink: 'Quick link',
  myTeam: 'My Team',
  seeAllTeam: 'See all Team Members',
  teamMemberCelebrate: '5 team members are celebrating their Birthday today!',
  seeWhoCeleb: ' See who is celebrating',
  takeTimeOff: '10 Team members are taking time off in next 7 days. ',
  viewTimeOff: 'View Time Offs',
  upcomingHoliday: 'Upcoming Holidays',
  seeAllHoliday: 'See All Holidays',
  pendingAction: 'My Pending Actions',
  views: ' Views',
  kudos: ' Kudos',
  loginScreen: {
    title: 'Hello, Welcome Back',
    subHeading: 'Sign in to access the portal',
    checkBoxText: 'Keep me signed in',
    buttonText: 'Sign In',
    ForgotPassText: 'Forgot Password?',
  },
};
